{{- if .Values.ingress.enabled -}}
{{- $fullName := include "food-order-ui.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "food-order-ui.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: "{{ .Values.service.name }}.{{ .Values.namespace }}.{{ .Values.clusterIP }}.{{ .Values.clusterDomain }}"
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ .Values.service.name }}
              servicePort: {{ .Values.service.port }}
{{- end }}
